### ISSUE TITLE
Block-scoped declarations (let, const, function, class) not yet supported outside strict mode

### ISSUE THREAD

**Issue by SeanGriffin** [finnursig/VideoScroller#1]
Receiving this error when adding VideoScroller.js and EasingFunctions.js to my page head "Block-scoped declarations (let, const, function, class) not yet supported outside strict mode".

**Comment by SeanGriffin** [comment]
Documentation says videoscroller has no dependencies on any other files so I assume i'm not missing any files and it does not state a need for an strict mode settings in the installation and usage instructions.

**Comment by SeanGriffin** [comment]
Ok I think I know whats going on. The SRC is different than the distributed code. the minified version is not based on the unminifed source.

**Comment by finnursig** [comment]
Hey, sorry for slow response.

All the source code is being run through babel so it does not use ES6 features in the distributed files.

Did you get it working ?

**Comment by SeanGriffin** [comment]
I did. I unminifed the final js and was able to work on that. I might
suggest updating the onscroll listen to watch for keyframes as its firing
its functions far more than it needs too causing the FPS to dip below 30.

On Thu, Sep 17, 2015 at 9:53 AM, Finnur Sigurðsson <notifications@github.com

> wrote:
> 
> Hey, sorry for slow response.
> 
> All the source code is being run through babel so it does not use ES6
> features in the distributed files.
> 
> Did you get it working ?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/finnursig/VideoScroller/issues/1#issuecomment-141112166
> .

## 

---

Sean Anteau

Front End Developer

seana@griffintechnology.com

419-262-0470

Griffin Technology

2030 Lindell Ave., Nashville, TN 37203 USA

## 

This message and any attachments should be treated as confidential 
information of Griffin Technology, Inc.

**Comment by finnursig** [comment]
Great, ill look into limiting the scroll event for future releases.

Thanks.
